### ISSUE TITLE
Custom validation in InlineFormSet

### ISSUE THREAD

**Issue by trepmag** [AndrewIngram/django-extra-views#165]
Hello,

I need to implement a custom validation for a InlineFormSet instantiated by a CreateWithInlinesView view but it appear that the clean() method in my inline formset is not triggered.

I was referring to this django documentation https://docs.djangoproject.com/en/1.11/topics/forms/formsets/#custom-formset-validation

```
class MyInlineFormset(InlineFormSet):
    model = my_model
    form_class = MyForm

    def clean(self):
        cleaned_data = super().clean()
        // Need to do a forms.ValidationError("Something need to be so...")
        return cleaned_data
```

**Comment by jonashaag** [comment]
Agreed, PR welcome

**Comment by trepmag** [comment]
While digging into the code I could figure how to pass to `formset_factory()` (and other variations like inlineformset_factory(), ...) function the `formset` parameter so that you can implements a custom validation as in https://docs.djangoproject.com/en/1.11/topics/forms/formsets/#custom-formset-validation.

So you need to implement your custom validation in a base formset class which would looks as follow for `InlineFormset`:
```
MyCustomBaseInlineFormset(forms.models.BaseInlineFormSet):
    def clean(self):
        # code here...
        pass
```
Then in the `InlineFormSet` you assign the above class to the `formset_class` attribute:
```
class MyInlineFormset(InlineFormSet):
    model = my_model
    form_class = MyForm
    formset_class = MyCustomBaseInlineFormset   # which will be passed into the formset argument of inlineformset_factory().
```

So this works but wasn't obvious as in InlineFormSet you can specify the `factory_kwargs` attribute into which you might think you could add the `formset` key but that doesn't works...

**Comment by sdolemelipone** [comment]
Yes as the docs specify, ``InlineFormSet`` isn't a subclass of Django's InlineFormSet class at all, but is instead a Mixin class to create an ``InlineFormSet`` from ``inlineformset_factory``. That mixin class can be repurposed to handle just one InlineFormSet within a view which contains multiple InlineFormSets. Took me some time to get my head around that too. The docs specifically demonstrate how to override clean() [here](https://github.com/AndrewIngram/django-extra-views/blob/master/docs/misc.rst#miscellaneous).

I'd be much happier if it was called ``InlineFormSetFactory`` instead of ``InlineFormSet`` as then the name describes what it is doing. @jonashaag let me know if you would like a pull request to make that change (and to all other mixins, e.g. ``FormSetFactoryMixin`` etc.). We'd probably have to maintain the old names with deprecation warnings? Or maybe that's all just too much trouble...

It should be possible to set ``formset`` within the ``factory_kwargs`` but for some reason we unnecessarily set ``BaseInlineFormSetMixin.formset_class = BaseInlineFormSet`` which will therefore override the value you set in ``factory_kwargs``. There's no reason to do that as ``inlineformset_factory`` already knows that the default value for formset_class is ``BaseInlineFormSet``, so we should change that. I have a PR ready to go on that one.

**Comment by jonashaag** [comment]
@sdolemelipone Fully agree with you. Renaming the stuff with deprecation path is a great suggestion and I think it's worth the trouble (if you're willing to do all the work :-D)

**Comment by sdolemelipone** [comment]
This was resolved by the merge, closing!
